// GENERATED BY split_app_theme_config.py
// APP_THEME_EXTRACTED_V1
//
// Application-owned theme configuration.
// Keep MaterialApp composition in lib/app/app.dart and theme details here.

import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:gl_mobile_app/design_system/kit.dart';
import 'package:super_auto_suggestion_box/super_auto_suggestion_box.dart';

// APP_READABILITY_THEME_V2
// Larger mobile typography with stronger Arabic readability.
//
// Important:
// SuperTextTheme.superCopyWith(...) can tune the branded styles, but some
// SuperCore widgets also read Material bodySmall/caption directly. The app-level
// minimum text scale installed in MaterialApp.builder below covers those slots
// too, without changing every screen/widget individually.
SuperTextTheme _buildReadableTextTheme({required bool isArabic}) {
  final bodyFont = isArabic
      ? GoogleFonts.ibmPlexSansArabic()
      : GoogleFonts.inter();
  final displayFont = isArabic ? GoogleFonts.cairo() : GoogleFonts.manrope();

  final base = SuperTextTheme(
    bodyFont: bodyFont,
    otherFont: displayFont,
    isArabic: isArabic,
  );

  return base.superCopyWith(
    headlineSm: base.headlineSm.copyWith(
      fontSize: isArabic ? 26 : 25,
      fontWeight: FontWeight.w700,
      height: isArabic ? 1.45 : 1.28,
      letterSpacing: isArabic ? 0 : -0.20,
    ),
    titleMd: base.titleMd.copyWith(
      fontSize: isArabic ? 21 : 20,
      fontWeight: FontWeight.w700,
      height: isArabic ? 1.50 : 1.35,
      letterSpacing: isArabic ? 0 : -0.10,
    ),
    bodyLg: base.bodyLg.copyWith(
      fontSize: isArabic ? 19 : 18,
      fontWeight: FontWeight.w500,
      height: isArabic ? 1.60 : 1.50,
      letterSpacing: 0,
    ),
    bodySm: base.bodySm.copyWith(
      fontSize: isArabic ? 17 : 16,
      fontWeight: FontWeight.w500,
      height: isArabic ? 1.60 : 1.50,
      letterSpacing: 0,
    ),
    labelMd: base.labelMd.copyWith(
      fontSize: isArabic ? 15 : 14,
      fontWeight: FontWeight.w700,
      height: isArabic ? 1.50 : 1.35,
      letterSpacing: isArabic ? 0 : 0.20,
    ),
    labelSm: base.labelSm.copyWith(
      fontSize: isArabic ? 13.5 : 13,
      fontWeight: FontWeight.w600,
      height: isArabic ? 1.50 : 1.35,
      letterSpacing: isArabic ? 0 : 0.10,
    ),
    mono: base.mono.copyWith(
      fontSize: 16,
      fontWeight: FontWeight.w500,
      height: 1.40,
    ),
    eyebrow: base.eyebrow.copyWith(
      fontSize: isArabic ? 14 : 13.5,
      fontWeight: FontWeight.w700,
      height: isArabic ? 1.50 : 1.35,
      letterSpacing: isArabic ? 0 : 0.55,
    ),
  );
}

Color _readableTone(Color foreground, Color background, double opacity) {
  return Color.alphaBlend(
    foreground.withValues(alpha: opacity),
    background,
  );
}

double _minimumReadableTextScale(Locale? locale) {
  final effectiveLocale =
      locale ?? WidgetsBinding.instance.platformDispatcher.locale;

  // Arabic glyphs generally need a little more physical size to match Latin
  // readability at the same nominal sp value.
  return effectiveLocale.languageCode.toLowerCase() == 'ar' ? 1.18 : 1.14;
}

SuperMaterialThemeData _buildReadableAppTheme({
  required Brightness brightness,
  required Locale? locale,
}) {
  final effectiveLocale =
      locale ?? WidgetsBinding.instance.platformDispatcher.locale;
  final isArabic = effectiveLocale.languageCode.toLowerCase() == 'ar';
  final isDark = brightness == Brightness.dark;
  final palette = SuperPalette.bluePalette;
  final typography = _buildReadableTextTheme(isArabic: isArabic);

  final base = isDark
      ? SuperMaterialThemeData.dark(
          palette: palette,
          textTheme: typography,
          primaryTextTheme: typography,
        )
      : SuperMaterialThemeData.light(
          palette: palette,
          textTheme: typography,
          primaryTextTheme: typography,
        );

  final colors = base.colorScheme;

  final fg2 = _readableTone(
    colors.onSurface,
    colors.surface,
    isDark ? 0.90 : 0.86,
  );
  final fg3 = _readableTone(
    colors.onSurface,
    colors.surface,
    isDark ? 0.80 : 0.76,
  );
  final fg4 = _readableTone(
    colors.onSurface,
    colors.surface,
    isDark ? 0.68 : 0.64,
  );

  final readableSuperTheme = base.superTheme.copyWith(
    fg2: fg2,
    fg3: fg3,
    fg4: fg4,
  );

  final baseCardTheme = SuperCardTheme.fromCardTheme(base.cardTheme);
  final cardColor = isDark
      ? colors.surfaceContainerHigh
      : colors.surfaceContainerLowest;
  final cardBorder = _readableTone(
    colors.onSurface,
    cardColor,
    isDark ? 0.30 : 0.20,
  );

  final readableCardTheme = baseCardTheme.copyWith(
    color: cardColor,
    surfaceTintColor: Colors.transparent,
    elevation: isDark ? 0 : 0.5,
    shadowColor: colors.shadow.withValues(alpha: isDark ? 0.26 : 0.10),
    borderColor: cardBorder,
    selectedBorderColor: colors.primary,
    shape: RoundedRectangleBorder(
      borderRadius: const BorderRadius.all(Radius.circular(12)),
      side: BorderSide(color: cardBorder, width: 1),
    ),
  );

  final readable = base.copyWith(
    superTheme: readableSuperTheme,
    textTheme: typography.colorize(colors.onSurface, fg3),
    primaryTextTheme: typography.colorize(colors.onPrimary, colors.onPrimary),
    hintColor: fg3,
    unselectedWidgetColor: fg3,
    dividerColor: cardBorder,
    cardColor: cardColor,
    cardTheme: readableCardTheme,
  );

  return readable.copyWith(
    extensions: [
      SuperAutoSuggestionsBoxThemeData.fromMaterialTheme(readable),
    ],
  );
}

/// Builds the application theme for the requested brightness and locale.
SuperMaterialThemeData buildAppTheme({
  required Brightness brightness,
  required Locale? locale,
}) {
  return _buildReadableAppTheme(
    brightness: brightness,
    locale: locale,
  );
}

/// Returns the minimum app text scale used for readability.
double minimumAppTextScale(Locale? locale) {
  return _minimumReadableTextScale(locale);
}
