// ============================================================
// GeniusLink Mobile — Super Core application theme
// File placement: lib/app/theme/app_theme.dart
// ============================================================

import 'package:super_core/super_core.dart';

/// The complete application Material theme is generated by `super_core`.
///
/// Mobile intentionally keeps its existing dark-only behavior while all
/// Material components and focused Super packages resolve the same palette,
/// typography, spacing, radii, motion, and responsive control metrics.
SuperMaterialThemeData buildMobileTheme() =>
    SuperMaterialThemeData.dark(palette: SuperPalette.bluePalette);
