// MOBILE_DASHBOARD_COMPONENTIZATION_V3
// Generated by refactor_mobile_dashboard_components.py.
// Feature section composition. Generic visual layout lives in design_system.

import 'package:flutter/material.dart';
import 'package:super_core/super_core.dart';

import '../controllers/mobile_dashboard_controller.dart';
import 'mobile_dashboard_attention.dart';
import 'mobile_dashboard_erp_overview.dart';
import 'mobile_dashboard_metrics.dart';
import 'mobile_dashboard_offline_banner.dart';
import 'mobile_dashboard_overview.dart';
import 'mobile_dashboard_quick_actions.dart';
import 'mobile_dashboard_recent_operations.dart';
import 'mobile_dashboard_shared.dart';
import 'mobile_dashboard_skeleton.dart';
import 'mobile_dashboard_theme.dart';
import 'mobile_dashboard_view_data.dart';

typedef MobileDashboardToastCallback = void Function(String message);

/// Composes the complete scrollable content area of the mobile
/// dashboard.
///
/// This is a feature-composition widget: it may depend on [MobileDashboardViewData]
/// and feature callbacks, while generic layout remains delegated to reusable
/// presentation components.
///
/// Example:
///
/// ```dart
/// MobileDashboardSectionContent(
///   dashboard: dashboard,
///   online: true,
///   scrollController: scrollController,
///   onRefresh: refreshDashboard,
///   onToast: showDashboardToast,
///   onOpenActions: openActions,
///   onToggleView: toggleView,
///   onCurrencyChanged: changeCurrency,
///   onPeriodChanged: changePeriod,
///   onMetricSelected: selectMetric,
/// )
/// ```
///
/// The example assumes the variables and callbacks are owned by the surrounding
/// screen/controller.
class MobileDashboardSectionContent extends StatelessWidget {
  final MobileDashboardViewData dashboard;
  final bool online;
  final ScrollController scrollController;
  final RefreshCallback onRefresh;
  final MobileDashboardToastCallback onToast;
  final VoidCallback onOpenActions;
  final VoidCallback onToggleView;
  final ValueChanged<String> onCurrencyChanged;
  final ValueChanged<String> onPeriodChanged;
  final ValueChanged<String> onMetricSelected;

  const MobileDashboardSectionContent({
    super.key,
    required this.dashboard,
    required this.online,
    required this.scrollController,
    required this.onRefresh,
    required this.onToast,
    required this.onOpenActions,
    required this.onToggleView,
    required this.onCurrencyChanged,
    required this.onPeriodChanged,
    required this.onMetricSelected,
  });

  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        if (!online) const MobileDashboardOfflineBanner(),
        Expanded(
          child: RefreshIndicator(
            onRefresh: onRefresh,
            color: context.mdColors.primary,
            backgroundColor: context.mdTheme.surface,
            child: ListView(
              controller: scrollController,
              physics: const AlwaysScrollableScrollPhysics(),
              padding: MobileDashboardLayout.scrollPadding,
              children: [
                MobileDashboardHeroSection(
                  dashboard: dashboard,
                  onToast: onToast,
                ),
                const SizedBox(height: MobileDashboardLayout.heroSectionGap),
                MobileDashboardStatusSection(
                  dashboard: dashboard,
                  onToast: onToast,
                ),
                const SizedBox(height: MobileDashboardLayout.sectionGap),
                MobileDashboardFinancialOverviewSection(
                  dashboard: dashboard,
                  onToggleView: onToggleView,
                  onCurrencyChanged: onCurrencyChanged,
                  onPeriodChanged: onPeriodChanged,
                  onMetricSelected: onMetricSelected,
                ),
                const SizedBox(height: MobileDashboardLayout.sectionGap),
                MobileDashboardWorkflowSection(
                  dashboard: dashboard,
                  onToast: onToast,
                ),
                const SizedBox(height: MobileDashboardLayout.sectionGap),
                MobileDashboardQuickActionsSection(
                  dashboard: dashboard,
                  onToast: onToast,
                  onViewAll: onOpenActions,
                ),
                const SizedBox(height: MobileDashboardLayout.sectionGap),
                MobileDashboardRecentOperationsSection(
                  dashboard: dashboard,
                  onToast: onToast,
                ),
                const SizedBox(height: MobileDashboardLayout.sectionGap),
                MobileDashboardAttentionSection(
                  dashboard: dashboard,
                  onToast: onToast,
                ),
              ],
            ),
          ),
        ),
      ],
    );
  }
}

/// Composes the dashboard hero area from prepared feature data.
///
/// The section handles the feature-level loading/content choice and delegates the
/// actual presentation to the existing hero widgets.
///
/// Example:
///
/// ```dart
/// MobileDashboardHeroSection(
///   dashboard: dashboard,
///   onToast: showDashboardToast,
/// )
/// ```
class MobileDashboardHeroSection extends StatelessWidget {
  final MobileDashboardViewData dashboard;
  final MobileDashboardToastCallback onToast;

  const MobileDashboardHeroSection({
    super.key,
    required this.dashboard,
    required this.onToast,
  });

  @override
  Widget build(BuildContext context) {
    if (dashboard.loading) {
      return const MobileDashboardErpHeroSkeleton();
    }

    return MobileDashboardErpHero(
      profile: dashboard.profile,
      workspace: dashboard.workspace,
      currency: dashboard.currency,
      onPrimaryAction: () => onToast(dashboard.profile.primaryActionLabel),
    );
  }
}

/// Composes the dashboard status strip and its loading state.
///
/// Example:
///
/// ```dart
/// MobileDashboardStatusSection(
///   dashboard: dashboard,
///   onToast: showDashboardToast,
/// )
/// ```
class MobileDashboardStatusSection extends StatelessWidget {
  final MobileDashboardViewData dashboard;
  final MobileDashboardToastCallback onToast;

  const MobileDashboardStatusSection({
    super.key,
    required this.dashboard,
    required this.onToast,
  });

  @override
  Widget build(BuildContext context) {
    if (dashboard.loading) {
      return MobileDashboardStatusStripSkeleton(
        itemCount: dashboard.statusSkeletonCount,
      );
    }

    return MobileDashboardErpStatusStrip(
      title: dashboard.profile.statusTitle,
      items: dashboard.profile.statusItems,
      onItemTap: (item) => onToast(item.label),
    );
  }
}

/// Composes the financial-overview surface, controls, and selected
/// report view.
///
/// Business state remains in [MobileDashboardViewData] and the surrounding
/// controller; user interactions are returned through callbacks.
///
/// Example:
///
/// ```dart
/// MobileDashboardFinancialOverviewSection(
///   dashboard: dashboard,
///   onToggleView: toggleView,
///   onCurrencyChanged: changeCurrency,
///   onPeriodChanged: changePeriod,
///   onMetricSelected: selectMetric,
/// )
/// ```
class MobileDashboardFinancialOverviewSection extends StatelessWidget {
  final MobileDashboardViewData dashboard;
  final VoidCallback onToggleView;
  final ValueChanged<String> onCurrencyChanged;
  final ValueChanged<String> onPeriodChanged;
  final ValueChanged<String> onMetricSelected;

  const MobileDashboardFinancialOverviewSection({
    super.key,
    required this.dashboard,
    required this.onToggleView,
    required this.onCurrencyChanged,
    required this.onPeriodChanged,
    required this.onMetricSelected,
  });

  @override
  Widget build(BuildContext context) {
    return SuperSectionCard2(
      title: MobileDashboardCopy.financialOverviewTitle,
      subtitle: MobileDashboardCopy.financialOverviewSubtitle,
      trailing: null,
      accentColor: mobileDashboardMarkerColor(
        context,
        MobileDashboardDefaults.financialOverviewMarker,
      ),
      child: Column(
        children: [
          MobileDashboardControlsSection(
            dashboard: dashboard,
            onToggleView: onToggleView,
            onCurrencyChanged: onCurrencyChanged,
            onPeriodChanged: onPeriodChanged,
          ),
          const SizedBox(height: MobileDashboardLayout.controlsReportGap),
          MobileDashboardReportViewSection(
            dashboard: dashboard,
            onMetricSelected: onMetricSelected,
          ),
        ],
      ),
    );
  }
}

/// Composes the dashboard view, currency, and period controls.
///
/// The section translates current feature state into presentation widgets and
/// forwards changes to the caller instead of owning dashboard state locally.
///
/// Example:
///
/// ```dart
/// MobileDashboardControlsSection(
///   dashboard: dashboard,
///   onToggleView: toggleView,
///   onCurrencyChanged: changeCurrency,
///   onPeriodChanged: changePeriod,
/// )
/// ```
class MobileDashboardControlsSection extends StatelessWidget {
  final MobileDashboardViewData dashboard;
  final VoidCallback onToggleView;
  final ValueChanged<String> onCurrencyChanged;
  final ValueChanged<String> onPeriodChanged;

  const MobileDashboardControlsSection({
    super.key,
    required this.dashboard,
    required this.onToggleView,
    required this.onCurrencyChanged,
    required this.onPeriodChanged,
  });

  @override
  Widget build(BuildContext context) {
    if (dashboard.loading) {
      return const MobileDashboardControlsSkeleton();
    }

    return MobileDashboardControls(
      view: dashboard.view,
      currency: dashboard.currency,
      period: dashboard.period,
      currencies: dashboard.catalog.currencies,
      onToggleView: onToggleView,
      onCurrencyChanged: onCurrencyChanged,
      onPeriodChanged: onPeriodChanged,
    );
  }
}

/// Selects and composes the active cards, chart, or breakdown report
/// view for the dashboard.
///
/// Loading placeholders are selected through the same feature state, keeping the
/// screen-level composition declarative.
///
/// Example:
///
/// ```dart
/// MobileDashboardReportViewSection(
///   dashboard: dashboard,
///   onMetricSelected: selectMetric,
/// )
/// ```
class MobileDashboardReportViewSection extends StatelessWidget {
  final MobileDashboardViewData dashboard;
  final ValueChanged<String> onMetricSelected;

  const MobileDashboardReportViewSection({
    super.key,
    required this.dashboard,
    required this.onMetricSelected,
  });

  @override
  Widget build(BuildContext context) {
    if (dashboard.loading) {
      return switch (dashboard.view) {
        ReportView.cards => MobileDashboardMetricGridSkeleton(
          itemCount: dashboard.metricSkeletonCount,
        ),
        ReportView.chart => const MobileDashboardChartSkeleton(),
        ReportView.breakdown => const MobileDashboardBreakdownSkeleton(),
      };
    }

    return switch (dashboard.view) {
      ReportView.cards => MobileDashboardMetricGrid(
        cards: dashboard.selectedTab.cards,
        currency: dashboard.currency,
        period: dashboard.period,
        valueFor: dashboard.cardValue,
      ),
      ReportView.chart => MobileDashboardChartView(
        cards: dashboard.selectedTab.cards,
        currency: dashboard.currency,
        period: dashboard.period,
        selectedMetricId: dashboard.chartMetricId,
        axisLabels: dashboard.axisLabels,
        valueFor: dashboard.cardValue,
        onMetricSelected: onMetricSelected,
      ),
      ReportView.breakdown => MobileDashboardBreakdownView(
        cards: dashboard.selectedTab.cards,
        tabLabel: dashboard.selectedTab.label,
        currency: dashboard.currency,
        valueFor: dashboard.cardValue,
      ),
    };
  }
}

/// Composes workflow items or their loading skeleton for the selected
/// dashboard profile.
///
/// Example:
///
/// ```dart
/// MobileDashboardWorkflowSection(
///   dashboard: dashboard,
///   onToast: showDashboardToast,
/// )
/// ```
class MobileDashboardWorkflowSection extends StatelessWidget {
  final MobileDashboardViewData dashboard;
  final MobileDashboardToastCallback onToast;

  const MobileDashboardWorkflowSection({
    super.key,
    required this.dashboard,
    required this.onToast,
  });

  @override
  Widget build(BuildContext context) {
    if (dashboard.loading) {
      return MobileDashboardWorkflowSkeleton(
        itemCount: dashboard.workflowSkeletonCount,
      );
    }

    return MobileDashboardWorkflowPanel(
      title: dashboard.profile.workflowTitle,
      subtitle: dashboard.profile.workflowSubtitle,
      items: dashboard.profile.workflowItems,
      onItemTap: (item) => onToast(item.title),
    );
  }
}

/// Composes the current workspace quick actions and the optional
/// "view all" interaction.
///
/// Example:
///
/// ```dart
/// MobileDashboardQuickActionsSection(
///   dashboard: dashboard,
///   onToast: showDashboardToast,
///   onViewAll: openActions,
/// )
/// ```
class MobileDashboardQuickActionsSection extends StatelessWidget {
  final MobileDashboardViewData dashboard;
  final MobileDashboardToastCallback onToast;
  final VoidCallback onViewAll;

  const MobileDashboardQuickActionsSection({
    super.key,
    required this.dashboard,
    required this.onToast,
    required this.onViewAll,
  });

  @override
  Widget build(BuildContext context) {
    if (dashboard.loading) {
      return MobileDashboardQuickActionsSkeleton(
        itemCount: dashboard.quickActionSkeletonCount,
      );
    }

    return MobileDashboardQuickActions(
      title: MobileDashboardCopy.workspaceTitle(dashboard.selectedTab.label),
      actions: dashboard.selectedTab.actions,
      onActionTap: (action) =>
          onToast(MobileDashboardCopy.openingAction(action.label)),
      onViewAll: onViewAll,
    );
  }
}

/// Composes recent operations or their loading skeleton from prepared
/// dashboard presentation data.
///
/// Example:
///
/// ```dart
/// MobileDashboardRecentOperationsSection(
///   dashboard: dashboard,
///   onToast: showDashboardToast,
/// )
/// ```
class MobileDashboardRecentOperationsSection extends StatelessWidget {
  final MobileDashboardViewData dashboard;
  final MobileDashboardToastCallback onToast;

  const MobileDashboardRecentOperationsSection({
    super.key,
    required this.dashboard,
    required this.onToast,
  });

  @override
  Widget build(BuildContext context) {
    if (dashboard.loading) {
      return MobileDashboardRecentOperationsSkeleton(
        itemCount: dashboard.recentOperationsSkeletonCount,
      );
    }

    return MobileDashboardRecentOperations(
      title: dashboard.profile.operationsTitle,
      subtitle: MobileDashboardCopy.recentOperationsSubtitle,
      operations: dashboard.selectedTab.operations,
      currency: dashboard.currency,
      amountFor: dashboard.operationAmount,
      onViewAll: () => onToast(MobileDashboardCopy.openRegister),
    );
  }
}

/// Composes attention/exception items and their loading state.
///
/// Example:
///
/// ```dart
/// MobileDashboardAttentionSection(
///   dashboard: dashboard,
///   onToast: showDashboardToast,
/// )
/// ```
class MobileDashboardAttentionSection extends StatelessWidget {
  final MobileDashboardViewData dashboard;
  final MobileDashboardToastCallback onToast;

  const MobileDashboardAttentionSection({
    super.key,
    required this.dashboard,
    required this.onToast,
  });

  @override
  Widget build(BuildContext context) {
    if (dashboard.loading) {
      return MobileDashboardAttentionSkeleton(
        itemCount: dashboard.attentionSkeletonCount,
      );
    }

    return MobileDashboardAttentionList(
      title: dashboard.profile.attentionTitle,
      subtitle: MobileDashboardCopy.attentionSubtitle,
      items: dashboard.profile.attentionItems,
      onItemTap: (item) => onToast(item.label),
      trailing: MobileDashboardPill(
        label: MobileDashboardCopy.openItems(dashboard.openAttentionCount),
        color: context.mdColors.error,
      ),
    );
  }
}
