// MOBILE_DASHBOARD_COMPONENTIZATION_V3
// Generated by refactor_mobile_dashboard_components.py.
// Presentation data adapter/config for the mobile dashboard.

import 'package:flutter/material.dart';

import '../../../../core/state/load_status.dart';
import '../../domain/domain.dart';
import '../controllers/mobile_dashboard_controller.dart';

/// Adapts mobile-dashboard feature/domain state into values needed by
/// the presentation layer.
///
/// This class intentionally belongs to the feature layer. Generic design-system
/// components must not depend on it; feature sections use it to prepare widgets
/// and values for those components.
///
/// Example:
///
/// ```dart
/// final dashboard = MobileDashboardViewData(
///   catalog: catalog,
///   sectionId: sectionId,
///   state: state,
///   workspace: workspace,
/// );
///
/// final selectedTab = dashboard.selectedTab;
/// final currency = dashboard.currency;
/// ```
class MobileDashboardViewData {
  final MobileDashboardCatalog catalog;
  final String sectionId;
  final MobileDashboardState state;
  final MdWorkspace workspace;

  const MobileDashboardViewData({
    required this.catalog,
    required this.sectionId,
    required this.state,
    required this.workspace,
  });

  String get currency => state.cur;
  String get period => state.period;
  ReportView get view => state.view;
  String? get chartMetricId => state.chartMetric;
  bool get loading => state.status.isLoading;

  MdTab get selectedTab {
    if (catalog.tabs.isEmpty) {
      return MobileDashboardDefaults.emptyTab;
    }

    return catalog.tabs.firstWhere(
      (tab) => tab.id == state.tab,
      orElse: () => catalog.tabs.first,
    );
  }

  MdDashboardProfile get profile {
    final tab = selectedTab;
    return catalog.profiles[sectionId] ??
        catalog.profiles[tab.id] ??
        MobileDashboardDefaults.emptyProfile(sectionId, tab.label);
  }

  List<String> get axisLabels => catalog.axisLabels[period] ?? const <String>[];

  int get statusSkeletonCount => MobileDashboardDefaults.skeletonCount(
    profile.statusItems.length,
    MobileDashboardDefaults.statusSkeletonCount,
  );

  int get metricSkeletonCount => MobileDashboardDefaults.skeletonCount(
    selectedTab.cards.length,
    MobileDashboardDefaults.metricSkeletonCount,
  );

  int get workflowSkeletonCount => MobileDashboardDefaults.skeletonCount(
    profile.workflowItems.length,
    MobileDashboardDefaults.workflowSkeletonCount,
  );

  int get quickActionSkeletonCount {
    final actionsCount = selectedTab.actions.length;
    if (actionsCount == 0) {
      return MobileDashboardDefaults.quickActionSkeletonCount;
    }

    return actionsCount
        .clamp(
          MobileDashboardDefaults.minQuickActionSkeletonCount,
          MobileDashboardDefaults.quickActionSkeletonCount,
        )
        .toInt();
  }

  int get recentOperationsSkeletonCount =>
      MobileDashboardDefaults.skeletonCount(
        selectedTab.operations.length,
        MobileDashboardDefaults.recentOperationsSkeletonCount,
      );

  int get attentionSkeletonCount => MobileDashboardDefaults.skeletonCount(
    profile.attentionItems.length,
    MobileDashboardDefaults.attentionSkeletonCount,
  );

  int get openAttentionCount =>
      profile.attentionItems.fold<int>(0, (sum, item) => sum + item.count);

  double cardValue(MdCard card) => _scaledCurrencyValue(card.values[currency]);

  double operationAmount(MdOperation operation) {
    return _scaledCurrencyValue(operation.amounts[currency]);
  }

  double _scaledCurrencyValue(double? value) => (value ?? 0) * workspace.factor;
}

abstract final class MobileDashboardDefaults {
  static const financialOverviewMarker = MdMarker.positive;
  static const statusSkeletonCount = 3;
  static const metricSkeletonCount = 4;
  static const workflowSkeletonCount = 3;
  static const quickActionSkeletonCount = 8;
  static const minQuickActionSkeletonCount = 4;
  static const recentOperationsSkeletonCount = 5;
  static const attentionSkeletonCount = 3;
  static const emptyTab = MdTab(
    id: 'empty',
    label: 'Dashboard',
    cards: [],
    actions: [],
    operations: [],
  );

  static int skeletonCount(int itemCount, int fallbackCount) {
    return itemCount == 0 ? fallbackCount : itemCount;
  }

  static MdDashboardProfile emptyProfile(String sectionId, String title) {
    return MdDashboardProfile(
      sectionId: sectionId,
      eyebrow: MobileDashboardCopy.dashboardEyebrow,
      title: title,
      subtitle: '',
      primaryActionId: 'create',
      primaryActionLabel: MobileDashboardCopy.createAction,
      statusTitle: MobileDashboardCopy.statusTitle,
      workflowTitle: MobileDashboardCopy.workflowTitle,
      workflowSubtitle: '',
      operationsTitle: MobileDashboardCopy.operationsTitle,
      attentionTitle: MobileDashboardCopy.attentionTitle,
      statusItems: const [],
      workflowItems: const [],
      attentionItems: const [],
    );
  }
}

abstract final class MobileDashboardLayout {
  static const scrollPadding = EdgeInsets.fromLTRB(18, 16, 18, 32);
  static const sheetBorderRadius = BorderRadius.vertical(
    top: Radius.circular(22),
  );
  static const heroSectionGap = 22.0;
  static const sectionGap = 24.0;
  static const controlsReportGap = 12.0;
  static const toastIconSize = 15.0;
  static const toastIconGap = 8.0;
  static const toastWidth = 280.0;
}

abstract final class MobileDashboardDurations {
  static const toast = Duration(milliseconds: 1600);
}

abstract final class MobileDashboardCopy {
  static const dashboardEyebrow = 'Dashboard';
  static const createAction = 'Create';
  static const statusTitle = 'Status';
  static const workflowTitle = 'Workflow';
  static const operationsTitle = 'Operations';
  static const attentionTitle = 'Attention';
  static const financialOverviewTitle = 'Financial overview';
  static const financialOverviewSubtitle =
      'Consolidated values, movement, and period comparison';
  static const recentOperationsSubtitle =
      'Latest posted and in-process documents';
  static const attentionSubtitle = 'Control issues that require resolution';
  static const openRegister = 'Open register';

  static String openingAction(String label) => 'Opening $label';
  static String workspaceTitle(String tabLabel) => '$tabLabel workspace';
  static String openItems(int count) => '$count open';
}
